### ISSUE TITLE
support config file and command flag to start kvserver

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#248]
Using a config file to start kv server, like `./kv-server --config default.toml`, the config file format is toml. If no config file supplied, we will use the default configuration.

We should supply some command flags to control some vars, like server listening address, raft listening addr, log level, etc. We will use these flags even we use config file at the same time.

- [ ] support config file
- [ ] support more command flag

**Comment by overvenus** [comment]
Hi, I am planning to add config file feature, is there any `config.toml` template?

Is this appropriate if there was none?

```toml
[server]
# set listening address.
addr = "127.0.0.1:20166"
# if not set, use addr instead. set advertise listening address for client communication.
advertise-addr = "127.0.0.1:20167"
# set which dsn to use, warning: default is rocksdb without persistent.
dsn = "raftkv"
# set the path to rocksdb directory.
store = "/tmp/tikv/store"
# log level: trace, debug, info, warn, error, off.
log = "info"

[raft]
# set cluster id, must greater than 0.
cluster-id = 1
# set pd address, host:port
pd = ""
```
