### ISSUE TITLE
Proposal: Make big numbers human-readable

### ISSUE THREAD

**Issue by overvenus** [pingcap/tikv#772]
In [config-template.toml](https://github.com/pingcap/tikv/blob/master/etc/config-template.toml), some properties are hard to read, e.g.:

```toml
region-max-size = 83886080
region-split-size = 67108864
```

Maybe we should add a human readable representation, e.g.:

```toml
region-max-size = "80MB"
region-split-size = "64MB"
# or
# region-max-size = 83886080
# region-split-size = 67108864

pd-heartbeat-tick-interval = "5s"
# or
# pd-heartbeat-tick-interval = 5000
```

### File Size Conversion Table:

| Symbol   |      Name      |  Binary |  Number of bytes |  Equal to |
|----------|-------------:|------:|------:|------:|
| B | Byte  | 2^0 | 1 | 1B |
| KB | Kilobyte |   2^10 |   1024 |   1024 B |
| MB | Megabyte |   2^20 |    1,048,576 |    1024 KB |
| GB | Gigabyte |   2^30 |    1,073,741,824 |    1024 MB |
| TB | Terabyte |   2^40 |    1,099,511,627,776 |    1024 GB |
| PB | Petabyte |   2^50 |    1,125,899,906,842,624 |    1024 TB |

```
"1KB" = 1024
"1MB" = 1024 * 1024 = 1,048,576
"1.5MB" = 1.5 * 1024 * 1024 = 1,572,864
```

----------

### Time Conversion Table:

|  Symbol  |      Unit (s)      |  Definition |
|:----------|-------------:|------:|
| ns | 10^(-9) |   One billionth of one second |
| us | 10^(-6) |   One millionth of one second |
| ms | 10^(-3) |   	One thousandth of one second |
| s | 10^0 |   one second |
| ks | 10^3 |   One thousand seconds |

ref:

[File size - Wikipedia, the free encyclopedia](https://en.wikipedia.org/wiki/File_size)
[Orders of magnitude (time) - Wikipedia, the free encyclopedia](https://en.wikipedia.org/wiki/Orders_of_magnitude_(time))
