### ISSUE TITLE
use namazu to simulate slow disk condition

### ISSUE THREAD

**Issue by siddontang** [pingcap/tikv#846]
Now we meet some panics when etcd does fysnc too slow and pd requests etcd failed, we should simulate this conditions and guarantee that even the disk is slow, tikv can work well too. 

I think https://github.com/osrg/namazu is a good choice to do this, or any other tools? 

/cc @iamxy @v01dstar

**Comment by AkihiroSuda** [comment]
+1

Currently namazu does not support hooking `fsync`, but we can implement it and other calls easily.

**Comment by siddontang** [comment]
Cool @AkihiroSuda 

We will try it later.

**Comment by siddontang** [comment]
Ping @v01dstar 

Can we use namazu in docker now?

**Comment by siddontang** [comment]
Hi @AkihiroSuda 

I use namazu to test 3 PD + 3 TiKV + 1 PD in container mode, see https://gist.github.com/siddontang/d1903ef08bb7029039e23e7b38debefe

The config is:

```toml
# Policy for observing events and yielding actions
# You can also implement your own policy.
# Default: "random"
explorePolicy = "random"

[explorePolicyParam]
  # for Ethernet/Filesystem/Java inspectors, event are non-deterministically delayed.
  # minInterval and maxInterval are bounds for the non-deterministic delays
  # Default: 0 and 0
  minInterval = "0ms"
  maxInterval = "5ms"

  # for Ethernet/Filesystem inspectors, you can specify fault-injection probability (0.0-1.0).
  # Default: 0.0
  faultActionProbability = 0.0

  # for Process inspector, you can specify how to schedule processes
  # "mild": execute processes with randomly prioritized SCHED_NORMAL/SCHED_BATCH scheduler.
  # "extreme": pick up some processes and execute them with SCHED_RR scheduler. others are executed with SCHED_BATCH scheduler.
  # "dirichlet": execute processes with SCHED_DEADLINE scheduler. Dirichlet-distribution is used for deciding runtime values.
  # Default: "mild"
  procPolicy = "extreme"

[container]
  # Default: false
  enableEthernetInspector = true
  ethernetNFQNumber = 42
  # Default: true
  enableProcInspector = true
  procWatchInterval = "1s"
  # Default: true (for volumes (`-v /foo:/bar`))
  enableFSInspector = true
```

Is the config OK?
In my test, if I set `maxInterval` to about 30ms, I will wait a very long time for TiDB initialization, seem that the delay affects cluster seriously. @v01dstar 

I just `enableFSInspector`, does it work for container? or should I need to do more things? 
Thank you.
